### ISSUE TITLE
建议用 markdown 代替 org

### ISSUE THREAD

**Issue by Kinneyzhang** [advanceflow/Elisp#2]
Github对org格式的渲染支持并不是很好。我在翻译的过程中发现，org中跳转到特定文件的特定标题的链接和org的内链接，github不支持，还有一些缩进要想还原英文文档的格式，org处理起来也比较麻烦。

虽然是elisp文档，也不一定非得用org，文档本来就是看的，哪个方便用哪个就好了，markdown更通用，也支持更丰富复杂的格式。

**Comment by advanceflow** [comment]
你的建议很好，今天我也在考虑这个问题，刚刚添加了markdown格式的哈
