### ISSUE TITLE
关于最新一次 commit

### ISSUE THREAD

**Issue by calsys456** [advanceflow/Elisp#4]
前辈好！我看到您在最新一次 commit 中把 40 和 41 两份文档中单词 `Emacs` 两端的所有空格都去掉了，这样是否不太合适？包括 `GNU Emacs` 和 `Emacs Lisp` 这样的单词都收到了一些影响。

希望有所帮助 :P

**Comment by advanceflow** [comment]
刚刚修改过来了哈
