### ISSUE TITLE
哪里可以获取 28.1 版本的 elisp manual 英文版 

### ISSUE THREAD

**Issue by Kinneyzhang** [advanceflow/Elisp#7]
今天看到论坛的帖子又被顶上来了，才想起来自己之前打算优化 hashtable 这一章的翻译的😂。现在打算重新拾起，但是我看官网上的 elisp manual 的文章已经更新到了 28.2，不确定和 28.1 有多少不同，我该如何获取到 28.1 的英文文档作为翻译的参考呢？

**Comment by suliveevil** [comment]
非常神奇的是，我在 gnu ftp 里也没找到，可能是藏在安装包里吧。

我正在下载中……

**Comment by Kinneyzhang** [comment]
有找到吗？找到的话，可以分享一下嘛

**Comment by suliveevil** [comment]
~~要不我直接建个库吧，稍等我一下。~~

~~https://github.com/suliveevil/Emacs-Doc/tree/28.1~~

不太会用 Git branch, 我还是打个 tag 吧。

https://github.com/suliveevil/Emacs-Doc/releases/tag/emacs-doc-28.1

**Comment by Kinneyzhang** [comment]
Thanks! 👍

**Comment by suliveevil** [comment]
不客气 :P

**Comment by advanceflow** [comment]
刚刚在original文件夹下添加了28.1版本的elisp manual英文版
